site_name: DbMover/MySQL
site_url: http://dbmover.monomelodies.nl/mysql/docs/
repo_url: https://github.com/dbmover/mysql

pages:
- Home:
    - 'General documentation': 'index.md'
- Plugins:
    - 'Conditionals': 'conditionals.md'
    - 'Indexes and constraints': 'indexes-and-constraints.md'
    - 'Procedures': 'procedures.md'
    - 'Tables': 'tables.md'
    - 'Triggers': 'triggers.md'
